"""Database migration for the accounting core."""
ACCOUNTING_SQLITE_SCHEMA = r'''
CREATE TABLE accounting_settings(workspace_id TEXT PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,base_currency TEXT NOT NULL DEFAULT 'USD',fiscal_year_start TEXT NOT NULL DEFAULT '01-01',config_version INTEGER NOT NULL DEFAULT 1,config_hash TEXT NOT NULL,verification_state TEXT NOT NULL DEFAULT 'unverified',verified_by TEXT,verified_at TEXT,verification_note TEXT,invalidated_at TEXT,invalidation_reason TEXT);
CREATE TABLE accounts(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,code TEXT NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('asset','liability','equity','income','expense')),currency TEXT,active INTEGER NOT NULL DEFAULT 1,system_key TEXT,UNIQUE(workspace_id,code),UNIQUE(workspace_id,system_key));
CREATE TABLE fiscal_periods(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,name TEXT NOT NULL,starts_on TEXT NOT NULL,ends_on TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','locked')),UNIQUE(workspace_id,starts_on,ends_on));
CREATE TABLE parties(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,kind TEXT NOT NULL CHECK(kind IN ('customer','vendor','both')),name TEXT NOT NULL,email TEXT,tax_id TEXT,currency TEXT,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
CREATE TABLE items(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,sku TEXT NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'goods',income_account_id TEXT REFERENCES accounts(id),expense_account_id TEXT REFERENCES accounts(id),inventory_account_id TEXT REFERENCES accounts(id),tax_code TEXT,active INTEGER NOT NULL DEFAULT 1,UNIQUE(workspace_id,sku));
CREATE TABLE tax_codes(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,code TEXT NOT NULL,name TEXT NOT NULL,rate_bps INTEGER NOT NULL CHECK(rate_bps BETWEEN 0 AND 100000),sales_account_id TEXT REFERENCES accounts(id),purchase_account_id TEXT REFERENCES accounts(id),rounding TEXT NOT NULL DEFAULT 'half_up',verified INTEGER NOT NULL DEFAULT 0,UNIQUE(workspace_id,code));
CREATE TABLE document_sequences(workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,kind TEXT NOT NULL,prefix TEXT NOT NULL,next_number INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(workspace_id,kind));
CREATE TABLE documents(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,kind TEXT NOT NULL CHECK(kind IN ('sales_invoice','purchase_bill','credit_note','debit_note','payment','refund','opening_balance','inventory_adjustment')),number TEXT NOT NULL,party_id TEXT REFERENCES parties(id),currency TEXT NOT NULL,exchange_rate TEXT NOT NULL DEFAULT '1',issue_date TEXT NOT NULL,due_date TEXT,status TEXT NOT NULL CHECK(status IN ('draft','approved','posted','voided')),subtotal_minor INTEGER NOT NULL,total_tax_minor INTEGER NOT NULL,total_minor INTEGER NOT NULL,balance_minor INTEGER NOT NULL,memo TEXT,source_document_id TEXT REFERENCES documents(id),journal_id TEXT,created_by TEXT NOT NULL,approved_by TEXT,created_at TEXT NOT NULL,posted_at TEXT,UNIQUE(workspace_id,kind,number));
CREATE TABLE document_lines(id TEXT PRIMARY KEY,document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE RESTRICT,position INTEGER NOT NULL,item_id TEXT REFERENCES items(id),description TEXT NOT NULL,quantity TEXT NOT NULL,unit_price_minor INTEGER NOT NULL,discount_minor INTEGER NOT NULL DEFAULT 0,tax_code_id TEXT REFERENCES tax_codes(id),net_minor INTEGER NOT NULL,tax_minor INTEGER NOT NULL,total_minor INTEGER NOT NULL,account_id TEXT REFERENCES accounts(id),UNIQUE(document_id,position));
CREATE TABLE journals(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,number TEXT NOT NULL,effective_date TEXT NOT NULL,description TEXT NOT NULL,source_type TEXT NOT NULL,source_id TEXT,reference TEXT,currency TEXT NOT NULL,exchange_rate TEXT NOT NULL DEFAULT '1',reverses_journal_id TEXT REFERENCES journals(id),reversed_by_journal_id TEXT REFERENCES journals(id),created_by TEXT NOT NULL,approved_by TEXT,posted_at TEXT NOT NULL,checksum TEXT NOT NULL,UNIQUE(workspace_id,number),UNIQUE(workspace_id,source_type,source_id));
CREATE TABLE journal_lines(id TEXT PRIMARY KEY,journal_id TEXT NOT NULL REFERENCES journals(id) ON DELETE RESTRICT,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,position INTEGER NOT NULL,account_id TEXT NOT NULL REFERENCES accounts(id),party_id TEXT REFERENCES parties(id),item_id TEXT REFERENCES items(id),debit_minor INTEGER NOT NULL DEFAULT 0 CHECK(debit_minor>=0),credit_minor INTEGER NOT NULL DEFAULT 0 CHECK(credit_minor>=0),base_debit_minor INTEGER NOT NULL DEFAULT 0,base_credit_minor INTEGER NOT NULL DEFAULT 0,memo TEXT,UNIQUE(journal_id,position),CHECK((debit_minor=0)!=(credit_minor=0)));
CREATE INDEX idx_journal_lines_ws_account ON journal_lines(workspace_id,account_id);
CREATE TABLE settlements(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,payment_document_id TEXT NOT NULL REFERENCES documents(id),target_document_id TEXT NOT NULL REFERENCES documents(id),amount_minor INTEGER NOT NULL CHECK(amount_minor>0),created_at TEXT NOT NULL,UNIQUE(payment_document_id,target_document_id));
CREATE TABLE journal_reversals(original_journal_id TEXT PRIMARY KEY REFERENCES journals(id),reversal_journal_id TEXT NOT NULL UNIQUE REFERENCES journals(id),created_at TEXT NOT NULL);
CREATE TABLE bank_transactions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,account_id TEXT NOT NULL REFERENCES accounts(id),posted_on TEXT NOT NULL,description TEXT NOT NULL,amount_minor INTEGER NOT NULL,external_id TEXT,status TEXT NOT NULL DEFAULT 'unmatched',matched_journal_id TEXT REFERENCES journals(id),UNIQUE(workspace_id,account_id,external_id));
CREATE TRIGGER journals_no_update BEFORE UPDATE ON journals BEGIN SELECT RAISE(ABORT,'posted journals are immutable'); END;
CREATE TRIGGER journals_no_delete BEFORE DELETE ON journals BEGIN SELECT RAISE(ABORT,'posted journals are immutable'); END;
CREATE TRIGGER journal_lines_no_update BEFORE UPDATE ON journal_lines BEGIN SELECT RAISE(ABORT,'posted journal lines are immutable'); END;
CREATE TRIGGER journal_lines_no_delete BEFORE DELETE ON journal_lines BEGIN SELECT RAISE(ABORT,'posted journal lines are immutable'); END;
'''
