const $=s=>document.querySelector(s);if(MosaicAuth.require()){const identity=JSON.parse(localStorage.getItem('mosaicIdentity')||'{}');if($('#company'))$('#company').textContent=identity.workspace_name||'Your company';if($('#state'))$('#state').textContent='Ready · '+(identity.role||'owner');
const api=async(path,body,method)=>{const r=await fetch(path,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',...MosaicAuth.headers},body:body&&JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not continue');return d};
const add=(text,who='bot')=>{const x=document.createElement('div');x.className='msg '+who;x.textContent=text;$('#messages').appendChild(x);x.scrollIntoView({behavior:'smooth'})};
const KIND_LABEL={dashboard:'Dashboard',report:'Report',statutory_invoice:'Document layout'};
let draft=null;
function specRows(spec){return Object.entries(spec).map(([k,v])=>'<div class="buildspec-row"><b>'+label(k)+'</b><span>'+fmt(v)+'</span></div>').join('')}
function label(k){return k.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function fmt(v){if(Array.isArray(v))return v.map(x=>typeof x==='object'?JSON.stringify(x):String(x)).join(', ');if(typeof v==='object')return JSON.stringify(v);return String(v)}
function showReview(original,d){draft=d;$('#review-original').textContent=original;$('#review-spec').innerHTML='<div class="buildspec-row"><b>Type</b><span>'+(KIND_LABEL[d.kind]||d.kind)+'</span></div><div class="buildspec-row"><b>Name</b><span>'+d.name+'</span></div>'+specRows(d.specification)+(d.kind==='statutory_invoice'?'<div class="buildspec-row"><b>Legal status</b><span>Draft - your accountant confirms before filing</span></div>':'');$('#reviewPanel').hidden=false;$('#review-state').textContent='';$('#reviewPanel').scrollIntoView({behavior:'smooth'})}
$('#chat').onsubmit=async e=>{e.preventDefault();const text=$('#say').value.trim();if(!text)return;add(text,'user');$('#say').value='';try{const d=await api('/api/artifacts/chat',{message:text});add(d.message||'Draft ready - review it below.');showReview(text,d)}catch(x){add(x.message)}};
$('#confirm').onclick=async()=>{if(!draft)return;try{if(draft.kind==='statutory_invoice'){$('#review-state').textContent='Tax document layouts activate only with an active reviewed tax rules version. Complete the tax review first, then confirm here.';return}const d=await api('/api/artifacts/verify',{artifact_id:draft.id,reviewer_kind:'owner',note:'Owner reviewed the draft in the Build screen and confirmed it matches what they asked for'});$('#review-state').textContent='Saved and active.';draft=null;$('#reviewPanel').hidden=true;add('Saved. It is now active in your workspace.');loadBuilds()}catch(x){$('#review-state').textContent=x.message}};
$('#discard').onclick=()=>{draft=null;$('#reviewPanel').hidden=true};
async function loadBuilds(){try{const d=await api('/api/artifacts');const box=$('#builds');if(!d.artifacts.length){box.innerHTML='<p class="buildnote">Nothing built yet. Describe what you need above.</p>';return}box.innerHTML='';d.artifacts.forEach(a=>{const div=document.createElement('div');div.className='builditem';div.innerHTML='<div><b>'+a.name+'</b><small>'+(KIND_LABEL[a.kind]||a.kind)+' · '+a.status+(a.legal_status&&a.legal_status!=='not_applicable'?' · '+a.legal_status.replace(/_/g,' '):'')+'</small></div>';box.appendChild(div)})}catch(e){}}
$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;$('#file-state').textContent='Reading '+f.name+'...';try{if(/\.csv$/i.test(f.name)){$('#file-state').textContent='Spreadsheets go through the checked importer - opening it in a moment.';location.href='/migration';return}if(/\.(pdf|txt)$/i.test(f.name)){const buf=await f.arrayBuffer();const b64=btoa(String.fromCharCode(...new Uint8Array(buf)));const d=await api('/api/build/read-file',{name:f.name,data:b64});$('#file-state').textContent='Read '+f.name+'.';showReview(f.name+': '+(d.excerpt||'').slice(0,400),d.draft);return}throw Error('That file type is not supported yet - try a PDF or CSV.')}catch(x){$('#file-state').textContent=x.message}};
loadBuilds()}
