const $=s=>document.querySelector(s);if(MosaicAuth.require()){const identity=JSON.parse(localStorage.getItem('mosaicIdentity')||'{}');if($('#company'))$('#company').textContent=identity.workspace_name||'Your company';if($('#state'))$('#state').textContent='Ready · '+(identity.role||'owner');
const api=async(path,body,method)=>{const r=await fetch(path,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',...MosaicAuth.headers},body:body&&JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Could not continue');return d};
const add=(text,who='bot')=>{const x=document.createElement('div');x.className='msg '+who;x.textContent=text;$('#messages').appendChild(x);x.scrollIntoView({behavior:'smooth'})};
const KIND_LABEL={dashboard:'Dashboard',report:'Report',statutory_invoice:'Document layout'};
const PACK_LABEL={products:'Products',customers:'Customers',vendors:'Suppliers',stock:'Stock on hand',open_invoices:'Open invoices',open_bills:'Open bills',opening_balances:'Opening balances'};
let draft=null;
const label=k=>k.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const fmt=v=>Array.isArray(v)?v.map(x=>typeof x==='object'?JSON.stringify(x):String(x)).join(', '):(typeof v==='object'?JSON.stringify(v):String(v));
function specRows(spec){return Object.entries(spec).map(([k,v])=>'<div class="buildspec-row"><b>'+label(k)+'</b><span>'+fmt(v)+'</span></div>').join('')}
function fileB64(f){return f.arrayBuffer().then(buf=>{const u8=new Uint8Array(buf);let s='';for(let i=0;i<u8.length;i+=8192)s+=String.fromCharCode.apply(null,u8.subarray(i,i+8192));return btoa(s)})}
function showReview(original,d,unmapped){draft=d;$('#review-original').textContent=original;$('#review-spec').innerHTML='<div class="buildspec-row"><b>Type</b><span>'+(KIND_LABEL[d.kind]||d.kind)+'</span></div><div class="buildspec-row"><b>Name</b><span>'+d.name+'</span></div>'+specRows(d.specification)+(d.kind==='statutory_invoice'?'<div class="buildspec-row"><b>Legal status</b><span>Draft - your accountant confirms before filing</span></div>':'');$('#review-unmapped').textContent=unmapped&&unmapped.length?'Not used from your file: '+unmapped.join(', ')+'. Mention anything you still need in your own words above.':'';$('#reviewPanel').hidden=false;$('#review-state').textContent='';$('#reviewPanel').scrollIntoView({behavior:'smooth'})}
function targetButtons(box,run){box.innerHTML='';[['report','Build a report'],['dashboard','Build a dashboard'],['statutory_invoice','Build an invoice layout']].forEach(([target,text])=>{const b=document.createElement('button');b.type='button';b.className='buildtarget';b.textContent=text;b.onclick=()=>run(target);box.appendChild(b)})}
function showChoice(name,extraction,choices){const tb=$('#file-result-actions');tb.innerHTML='';const p=document.createElement('p');p.className='buildnote';p.textContent='Which report should this become?';tb.appendChild(p);choices.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='buildtarget';b.textContent=label(c);b.onclick=async()=>{tb.querySelectorAll('button').forEach(x=>x.disabled=true);try{const r=await api('/api/build/draft-from-extraction',{target:'report',extraction,hint:name+' '+c.replace(/_/g,' ')});showReview((extraction.summary||name)+' - '+label(c),r.draft,r.unmapped)}catch(x){$('#file-state').textContent=x.message;tb.querySelectorAll('button').forEach(x=>x.disabled=false)}};tb.appendChild(b)})}
function showExtraction(name,d){const box=$('#file-result');box.hidden=false;let rows=(d.fields||[]).map(f=>{const pct=Math.round((f.confidence||0)*100);return '<div class="buildfield'+(pct<60?' low':'')+'"><b>'+f.name+'</b><span>'+f.value+'</span><i>'+(pct<60?'check this':pct+'%')+'</i></div>'}).join('');$('#file-result-head').textContent=(d.document_type?label(d.document_type):'Document')+' from '+name+(d.summary?' - '+d.summary:'');$('#file-result-fields').innerHTML=rows||'<p class="buildnote">No fields were read clearly. Type what the document shows above instead.</p>';const tb=$('#file-result-actions');targetButtons(tb,async target=>{tb.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await api('/api/build/draft-from-extraction',{target,extraction:d,hint:name});if(r.needs_choice){showChoice(name,d,r.choices)}else{showReview((d.summary||name),r.draft,r.unmapped)}}catch(x){$('#file-state').textContent=x.message;tb.querySelectorAll('button').forEach(b=>b.disabled=false)}})}
async function stageImport(pack,csv){$('#file-state').textContent='Checking rows...';try{const d=await api('/api/migrations/stage',{kind:pack,csv,source_system:'build-upload'});const box=$('#file-result');box.hidden=false;$('#file-result-head').textContent=(PACK_LABEL[pack]||pack)+' import - '+d.row_count+' rows checked';let html='';if(d.errors&&d.errors.length){html='<p class="buildnote">'+d.errors.length+' problem'+(d.errors.length===1?'':'s')+' to fix first:</p>'+d.errors.slice(0,6).map(e=>'<div class="buildfield low"><b>Row '+e.row+'</b><span>'+e.error+'</span><i></i></div>').join('')}else{html='<p class="buildnote">All '+d.row_count+' rows check out. Control total: '+d.control_total_minor+' minor units. Nothing is applied yet.</p>';const b=document.createElement('button');b.type='button';b.className='buildtarget';b.textContent='Apply this import';b.onclick=async()=>{b.disabled=true;try{const r=await api('/api/migrations/apply',{batch_id:d.id});$('#file-result-fields').innerHTML='<p class="buildnote">Import applied and reconciled ('+r.status+'). '+r.rows.length+' records created.</p>';$('#file-result-actions').innerHTML=''}catch(x){$('#file-state').textContent=x.message;b.disabled=false}};$('#file-result-actions').innerHTML='';$('#file-result-actions').appendChild(b)}$('#file-result-fields').innerHTML=html;$('#file-state').textContent=''}catch(x){$('#file-state').textContent=x.message}}
$('#chat').onsubmit=async e=>{e.preventDefault();const text=$('#say').value.trim();if(!text)return;add(text,'user');$('#say').value='';try{const d=await api('/api/artifacts/chat',{message:text});add(d.message||'Draft ready - review it below.');showReview(text,d)}catch(x){add(x.message)}};
$('#confirm').onclick=async()=>{if(!draft)return;try{if(draft.kind==='statutory_invoice'){$('#review-state').textContent='Invoice layouts activate only with an active reviewed tax rules version. Complete the tax review first, then confirm here.';return}const d=await api('/api/artifacts/verify',{artifact_id:draft.id,reviewer_kind:'owner',note:'Owner reviewed the draft in the Build screen and confirmed it matches what they asked for'});$('#review-state').textContent='Saved and active.';draft=null;$('#reviewPanel').hidden=true;add('Saved. It is now active in your workspace.');loadBuilds()}catch(x){$('#review-state').textContent=x.message}};
$('#discard').onclick=()=>{draft=null;$('#reviewPanel').hidden=true};
async function loadBuilds(){try{const d=await api('/api/artifacts');const box=$('#builds');if(!d.artifacts.length){box.innerHTML='<p class="buildnote">Nothing built yet. Describe what you need above.</p>';return}box.innerHTML='';d.artifacts.forEach(a=>{const div=document.createElement('div');div.className='builditem';div.innerHTML='<div><b>'+a.name+'</b><small>'+(KIND_LABEL[a.kind]||a.kind)+' · '+a.status+(a.legal_status&&a.legal_status!=='not_applicable'?' · '+a.legal_status.replace(/_/g,' '):'')+'</small></div>';box.appendChild(div)})}catch(e){}}
$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;e.target.value='';$('#file-result').hidden=true;$('#file-state').textContent='Reading '+f.name+'...';try{const b64=await fileB64(f);const mime=f.type||'';if(/^image\//.test(mime)||/\.(png|jpe?g|webp)$/i.test(f.name)){const d=await api('/api/build/read-photo',{name:f.name,mime,data_b64:b64});$('#file-state').textContent='';showExtraction(f.name,d);return}const d=await api('/api/build/read-file',{name:f.name,mime,data_b64:b64});$('#file-state').textContent='';if(d.detected&&d.detected.type==='migration'){const box=$('#file-result');box.hidden=false;$('#file-result-head').textContent='This looks like '+(PACK_LABEL[d.detected.pack]||d.detected.pack).toLowerCase()+' data ('+d.characters+' characters read).';$('#file-result-fields').innerHTML='<p class="buildnote excerpt">'+d.excerpt.slice(0,300).replace(/</g,'&lt;')+(d.excerpt.length>300?'...':'')+'</p>'+(d.detected.missing_columns&&d.detected.missing_columns.length?'<p class="buildnote">Missing columns: '+d.detected.missing_columns.join(', ')+' - the checker will confirm.</p>':'');const tb=$('#file-result-actions');tb.innerHTML='';const b=document.createElement('button');b.type='button';b.className='buildtarget';b.textContent='Check these rows';b.onclick=()=>{b.disabled=true;stageImport(d.detected.pack,d.detected.csv)};tb.appendChild(b);return}const box=$('#file-result');box.hidden=false;$('#file-result-head').textContent=f.name+' - '+(d.kind==='pdf'?'PDF':'text')+', '+d.characters+' characters read on this computer';$('#file-result-fields').innerHTML='<p class="buildnote excerpt">'+d.excerpt.slice(0,600).replace(/</g,'&lt;')+(d.excerpt.length>600?'...':'')+'</p>';const tb=$('#file-result-actions');targetButtons(tb,async target=>{tb.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await api('/api/build/draft-from-extraction',{target,extraction:{document_type:(d.detected&&d.detected.hints||[]).join(' ')||'document',summary:d.excerpt.slice(0,280)},hint:f.name});if(r.needs_choice){showChoice(f.name,{document_type:(d.detected&&d.detected.hints||[]).join(' ')||'document',summary:d.excerpt.slice(0,280)},r.choices)}else{showReview(f.name+': '+d.excerpt.slice(0,200),r.draft,r.unmapped)}}catch(x){$('#file-state').textContent=x.message;tb.querySelectorAll('button').forEach(b=>b.disabled=false)}})}catch(x){$('#file-state').textContent=x.message}};
loadBuilds()}
