"""Source-backed tax configuration blueprints for Mosaic's second jurisdiction set."""
DATA={
'Australia':('GST','Australian Taxation Office','AUD','A$','A$75,000 GST turnover (special tests for non-profits and taxi/ride-sourcing)',[('Standard',10),('GST-free',0)],'Tax invoice; recipient identity for taxable sales of A$1,000 or more',[('ATO: GST registration','https://www.ato.gov.au/businesses-and-organisations/gst-excise-and-indirect-taxes/gst/registering-for-gst'),('ATO: Tax invoices','https://www.ato.gov.au/businesses-and-organisations/gst-excise-and-indirect-taxes/gst/tax-invoices')],'Classify GST-free, input-taxed, property, non-profit and ride-sourcing supplies.'),
'New Zealand':('GST','Inland Revenue New Zealand','NZD','NZ$','NZ$60,000 taxable activity turnover in 12 months',[('Standard',15),('Zero-rated',0)],'Taxable supply information; required fields scale with consideration',[('IRD: GST registration','https://www.ird.govt.nz/gst/registering-for-gst'),('IRD: Taxable supply information','https://www.ird.govt.nz/gst/tax-invoices-for-gst')],'Land, financial services, exports and mixed-use assets need transaction facts.'),
'Japan':('Consumption tax','National Tax Agency Japan','JPY','¥','Commonly ¥10 million base-period taxable sales, subject to special-period and election rules',[('Standard',10),('Eligible food/newspapers',8)],'Qualified invoice with issuer number and rate-separated totals',[('NTA: Consumption tax basics','https://www.nta.go.jp/english/taxes/consumption_tax/pdf/2025/simplified_02.pdf'),('NTA: Qualified invoice system','https://www.nta.go.jp/english/taxes/consumption_tax/pdf/2023/simplified_04.pdf')],'Confirm base/specified period, simplified taxation and transitional input-credit rules.'),
'South Korea':('VAT','National Tax Service Korea','KRW','₩','Taxpayer category depends on business type and statutory turnover tests',[('Standard',10),('Eligible exports',0)],'Electronic tax invoice with registration numbers and transmission status',[('NTS: Electronic tax invoices','https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=7697&mi=2458'),('NTS: VAT on electronic services','https://www.nts.go.kr/english/na/ntt/selectNttList.do?bbsId=30699&mi=11210')],'Simplified-tax eligibility and electronic invoice duties vary by business and turnover.'),
'Saudi Arabia':('VAT','Zakat, Tax and Customs Authority','SAR','SAR','Mandatory SAR375,000; voluntary from SAR187,500, subject to statutory tests',[('Standard',15),('Eligible zero-rated',0)],'FATOORA e-invoice; Phase 2 only after wave notification',[('ZATCA: VAT','https://zatca.gov.sa/en/RulesRegulations/Taxes/Pages/VAT.aspx'),('ZATCA: E-Invoicing','https://zatca.gov.sa/en/E-Invoicing/Pages/default.aspx')],'Confirm the taxpayer’s Phase 2 wave and technical onboarding before integration.'),
'South Africa':('VAT','South African Revenue Service','ZAR','R','Use the current SARS compulsory/voluntary registration test',[('Standard',15),('Eligible zero-rated',0)],'Full or abridged tax invoice with vendor VAT numbers',[('SARS: VAT registration','https://www.sars.gov.za/types-of-tax/value-added-tax/register-for-vat/'),('SARS: Tax invoices','https://www.sars.gov.za/businesses-and-employers/government/tax-invoices/')],'Verify current threshold, voluntary registration, zero-rating and exempt classification.'),
'Brazil':('IBS/CBS + legacy taxes','Receita Federal and CGIBS','BRL','R$','No single safe threshold: regime, state, municipality, product/service and transition year required',[('2026 CBS test',0.9),('2026 IBS test',0.1)],'Applicable NF-e/NFC-e/NFS-e model with transition fields',[('Receita Federal: 2026 reform guidance','https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/programas-e-atividades/reforma-tributaria-do-consumo/orientacoes-2026'),('CGIBS: 2026 transition guidance','https://www.cgibs.gov.br/comite-gestor-e-receita-federal-garantem-prazo-de-adaptacao-e-transicao-segura-para-contribuintes-do-ibs-e-da-cbs-em-2026')],'2026 is transitional. Never replace ICMS, ISS, IPI or PIS/COFINS with one rate.'),
'Mexico':('IVA','Servicio de Administración Tributaria','MXN','MX$','No general small-business IVA threshold; regime and transaction determine obligations',[('General',16),('Eligible border incentive',8),('Zero-rated',0)],'CFDI 4.0 with RFC, regime, postal code, uso CFDI and complements',[('SAT: CFDI Anexo 20','http://omawww.sat.gob.mx/tramitesyservicios/Paginas/anexo_20.htm'),('SAT: CFDI guide','http://omawww.sat.gob.mx/informacion_fiscal/factura_electronica/Documents/Gu%C3%ADaAnexo20.pdf')],'The 8% border incentive is not automatic; validate region, taxpayer and transaction.'),
'Indonesia':('PPN','Direktorat Jenderal Pajak','IDR','Rp','Confirm current PKP gross-turnover threshold and election status',[('Statutory rate',12),('General non-luxury effective burden',11),('Exports',0)],'Electronic Faktur Pajak with transaction code and validated tax base',[('DJP: Electronic tax invoices','https://www.pajak.go.id/id/peraturan/tata-cara-pembuatan-dan-pelaporan-faktur-pajak-berbentuk-elektronik'),('DJP: PER-1/PJ/2025 examples','https://www.pajak.go.id/sites/default/files/lampiranper01pj2025.pdf')],'Do not apply 12% universally; confirm luxury status, other-value base, facility and code.'),
'Philippines':('VAT','Bureau of Internal Revenue','PHP','₱','₱3 million gross-sales threshold, subject to current law and elections',[('Standard',12),('Eligible zero-rated',0)],'BIR invoice with TIN, registration and VAT breakdown',[('BIR: RR 11-2025','https://bir-cdn.bir.gov.ph/BIR/pdf/RR%20No.%2011-2025.pdf'),('BIR: official site','https://www.bir.gov.ph/')],'E-invoicing is phased; confirm taxpayer classification and latest BIR notice.'),
'Thailand':('VAT','Thai Revenue Department','THB','฿','THB1.8 million annual turnover for covered activities',[('Current reduced rate - verify expiry',7),('Eligible zero-rated',0)],'Tax invoice with taxpayer IDs, branch, value and VAT',[('Revenue Department: VAT','https://www.rd.go.th/english/6043.html'),('Revenue Department: VAT invoice law','https://www.rd.go.th/english/37741.html')],'The 7% rate is temporary; verify extension for the transaction date and exemptions.'),
'Switzerland':('VAT','Swiss Federal Tax Administration','CHF','CHF','CHF100,000 worldwide turnover from non-excluded supplies, with special tests',[('Standard',8.1),('Reduced',2.6),('Accommodation',3.8)],'Invoice with identities, VAT number, date, supply, value and tax',[('FTA: VAT liability','https://www.estv.admin.ch/en/vat-tax-liability'),('FTA: VAT registration','https://www.estv.admin.ch/en/register-for-vat')],'Confirm establishment, worldwide turnover, excluded supplies and reporting method.')}
BANDS={'Australia':['Up to A$75,000','Above A$75,000'],'New Zealand':['Up to NZ$60,000','Above NZ$60,000'],'Japan':['Up to ¥10 million base-period sales','Above ¥10 million base-period sales'],'South Korea':['Any turnover'],'Saudi Arabia':['Up to SAR187,500','SAR187,500 – 375,000','Above SAR375,000'],'South Africa':['Up to current threshold','Above current threshold'],'Brazil':['Any turnover'],'Mexico':['Any turnover'],'Indonesia':['Up to Rp4.8 billion','Above Rp4.8 billion'],'Philippines':['Up to ₱3 million','Above ₱3 million'],'Thailand':['Up to THB1.8 million','Above THB1.8 million'],'Switzerland':['Up to CHF100,000 worldwide','Above CHF100,000 worldwide']}
REG={'Australia':['GST registered','Not registered'],'New Zealand':['GST registered','Not registered'],'Japan':['Qualified invoice issuer','Taxable - not qualified issuer','Tax-exempt business'],'South Korea':['General VAT taxpayer','Simplified taxpayer'],'Saudi Arabia':['VAT registered','Voluntary registration','Not registered'],'South Africa':['VAT vendor','Voluntary registration','Not registered'],'Brazil':['Simples Nacional','Lucro Presumido','Lucro Real'],'Mexico':['VAT registered','RESICO','Not registered'],'Indonesia':['PKP registered','Non-PKP'],'Philippines':['VAT registered','Non-VAT registered'],'Thailand':['VAT registered','Not registered'],'Switzerland':['VAT registered','Not registered']}
SUP={c:['Within '+c,c+' + exports'] for c in DATA};SUP['Brazil']=['Within my state','Across Brazilian states','Brazil + exports'];SUP['Indonesia']=['General taxable goods/services','Luxury taxable goods','Indonesia + exports']
SUB={'Brazil':('Which Brazilian state is the establishment in? ICMS and document rules differ.',['São Paulo','Rio de Janeiro','Minas Gerais','Paraná','Rio Grande do Sul','Other state']),'Mexico':('Which VAT region applies? The border incentive is conditional.',['General region','Northern border incentive region','Southern border incentive region']),'Switzerland':('Is the business established in Switzerland or abroad?',['Swiss-established','Foreign-established'])}
def make_pack(a,today):
 tax,auth,code,sym,threshold,rates,invoice,sources,caveat=DATA[a['country']];reg=a.get('registration','Undecided');registered=not any(x in reg for x in ('Not registered','Non-PKP','Tax-exempt'))
 return {'jurisdiction':a['country'],'subdivision':a.get('subdivision'),'tax_name':tax,'authority':auth,'currency':{'code':code,'symbol':sym},'registration':{'type':reg,'registered':registered,'label':'Tax registration identifier' if registered else 'Registration review required','threshold':threshold},'rates':{'structure':'Transaction-classified rates; never infer from country alone','slabs':[{'band':b,'rate':r} for b,r in rates],'note':caveat},'rules':['Taxable supply → validate product/service, customer and place before rate'], 'invoice':[invoice],'credits':'Input credit only with registration, eligible transaction and valid document' if registered else 'No input claim until registration is confirmed','returns':['Return frequency and form must match the registered taxpayer profile'],'validations':[{'check':'Registration','status':'Confirm identifier, effective date and category'},{'check':'Transaction facts','status':'Confirm product/service, customer, place and exemptions'},{'check':'Electronic invoicing','status':'Enable only after coverage, mandate date and enrollment are verified'}],'warnings':[caveat]+([] if registered else ['Do not charge or claim input tax until registration is confirmed.']),'reverse_charge':'Validate cross-border/designated-supply reverse charge per transaction','workflows':['Sale → classify → validate registration/place/customer → calculate → issue required document → audit'],'kpi':tax+' payable' if registered else 'Registration threshold watch','sources':[{'title':t,'url':u} for t,u in sources],'effective':today}
