const $=s=>document.querySelector(s);let schema,session,current,selected;const identity=JSON.parse(localStorage.getItem('mosaicIdentity')||'{}');if($('#rail-company'))$('#rail-company').textContent=identity.workspace_name||'Your company';
async function api(path,method='GET',body){let r=await fetch(path,{method,headers:{'Content-Type':'application/json',...MosaicAuth.headers},body:body&&JSON.stringify(body)});let j=await r.json();if(!r.ok)throw Error(j.error||'Could not continue');return j}
async function begin(){if(!MosaicAuth.require())return;schema=await api('/api/onboarding/schema');let id=localStorage.mosaicOnboarding;if(id){try{session=await api('/api/onboarding/session?id='+encodeURIComponent(id))}catch(e){localStorage.removeItem('mosaicOnboarding')}}if(!session){session=await api('/api/onboarding/start','POST',{});localStorage.mosaicOnboarding=session.id}$('#connect').hidden=true;render()}
function render(){if(session.status==='ready'||session.status==='needs_review'||session.status==='applied'){showSummary();return}current=schema.questions.find(q=>q.key===session.current_question);let n=schema.questions.indexOf(current);$('#interview').hidden=false;$('#bar').value=(n/schema.questions.length)*100;$('#rail-step').textContent='Question '+(n+1)+' of '+schema.questions.length;$('#question-step').textContent=String(n+1).padStart(2,'0')+' / '+String(schema.questions.length).padStart(2,'0');$('#question').textContent=current.text;$('#why').textContent='Why Mosaic asks: '+current.why;$('#examples').textContent=current.examples?'For example: '+current.examples.join(' / '):'';$('#answer').hidden=current.type==='choice'||current.type==='multi';$('#answer').value='';selected=current.type==='multi'?[]:null;$('#options').innerHTML='';(current.options||[]).forEach(o=>{let b=document.createElement('button');b.textContent=o;b.onclick=()=>{if(current.type==='multi'){selected.includes(o)?selected.splice(selected.indexOf(o),1):selected.push(o);b.classList.toggle('selected',selected.includes(o))}else{selected=o;[...$('#options').children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}};$('#options').appendChild(b)})}
async function save(){let value=current.type==='text'?$('#answer').value:selected;if(!value||(Array.isArray(value)&&!value.length)){ $('#saved').textContent='Please answer in the way that fits your business.';return}session=await api('/api/onboarding/answer','POST',{id:session.id,key:current.key,value});$('#saved').textContent='Saved';render()}
function rail(step){let li=document.querySelectorAll('.rail-progress li');li[1].className=step>=2?'done':'on';li[1].querySelector('i').textContent=step>=2?'\u2713':'2';li[2].className=step>=3?'done':(step===2?'on':'');li[2].querySelector('i').textContent=step>=3?'\u2713':'3'}
function showApplied(){rail(3);let bar=document.querySelector('#summary .card-bar span');if(bar)bar.textContent='LIVE';let note=document.querySelector('.summary-note');if(note)note.textContent='Your Mosaic is ready. The setup you reviewed is now live in your workspace.';let acts=document.querySelector('.summary-actions');if(acts)acts.innerHTML='<p id="apply-state"></p><a class="open-workspace" href="/operations">Open your workspace \u2192</a>'}
async function applySetup(){let b=$('#apply');if(!b)return;b.disabled=true;$('#apply-state').textContent='Applying your setup\u2026';try{await api('/api/onboarding/apply','POST',{id:session.id});session.status='applied';showApplied()}catch(e){b.disabled=false;$('#apply-state').textContent=e.message}}
function showSummary(){$('#interview').hidden=true;$('#summary').hidden=false;rail(session.status==='applied'?3:2);let i=session.inference;$('#review').innerHTML='<b>Business:</b> '+(i.owner_summary.business||'Your business')+'<br><b>First goal:</b> '+(i.owner_summary.first_goal||'Not answered')+'<br><b>Why features are enabled:</b><ul>'+i.explanations.map(x=>'<li>'+x.because+'</li>').join('')+'</ul>'+(session.contradictions.length?'<b>One thing to clarify:</b> '+session.contradictions.map(x=>x.message).join(' '):'<b>Ready for owner and professional review.</b>');if(session.status==='applied')showApplied()}
$('#start').onclick=()=>begin().catch(e=>$('#state').textContent=e.message);$('#signout').onclick=()=>MosaicAuth.clear();if(MosaicAuth.token)begin().catch(e=>$('#state').textContent=e.message);$('#save').onclick=()=>save().catch(e=>$('#saved').textContent=e.message);$('#apply').onclick=()=>applySetup();
