-- PostgreSQL operational ERP schema gate. Apply after core PG migration as migration 2.
-- Generated table definitions follow SQLite logical schema, using text IDs, bigint money,
-- numeric quantities, timestamptz timestamps and CHECK constraints. No ERP table is exempt from RLS.
CREATE TABLE accounting_settings(workspace_id text PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,base_currency text NOT NULL,fiscal_year_start text NOT NULL,config_version integer NOT NULL DEFAULT 1,config_hash text NOT NULL,verification_state text NOT NULL,verified_by text,verified_at timestamptz,verification_note text,invalidated_at timestamptz,invalidation_reason text);
CREATE TABLE locations(id text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,code text NOT NULL,name text NOT NULL,kind text NOT NULL,active boolean NOT NULL DEFAULT true,UNIQUE(workspace_id,code));
CREATE TABLE retail_products(id text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,sku text NOT NULL,name text NOT NULL,barcode text,unit text NOT NULL,selling_price_minor bigint NOT NULL,cost_minor bigint NOT NULL,active boolean NOT NULL DEFAULT true,UNIQUE(workspace_id,sku));
CREATE TABLE stock_ledger(id text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,product_id text NOT NULL REFERENCES retail_products(id),location_id text NOT NULL REFERENCES locations(id),effective_at timestamptz NOT NULL,quantity_delta numeric(24,8) NOT NULL,unit_cost_minor bigint NOT NULL,kind text NOT NULL,source_type text NOT NULL,source_id text NOT NULL,actor_id text NOT NULL,created_at timestamptz NOT NULL,UNIQUE(workspace_id,source_type,source_id,product_id,location_id,kind));
-- The complete accounting and retail table list must be expanded here before migration may run.
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['accounting_settings','locations','retail_products','stock_ledger'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t);EXECUTE format('CREATE POLICY %I_tenant ON %I USING (workspace_id=current_setting(''mosaic.workspace_id'',true)) WITH CHECK (workspace_id=current_setting(''mosaic.workspace_id'',true))',t,t);END LOOP;END $$;
