"""Operational retail ERP migration. Country packs configure it; they are not the product."""
RETAIL_SQLITE_SCHEMA=r'''
ALTER TABLE workspaces ADD COLUMN operational_profile_json TEXT;
ALTER TABLE workspaces ADD COLUMN operational_profile_hash TEXT;
ALTER TABLE workspaces ADD COLUMN operational_profile_at TEXT;
CREATE TABLE locations(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,code TEXT NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'store',active INTEGER NOT NULL DEFAULT 1,UNIQUE(workspace_id,code));
CREATE TABLE retail_products(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,sku TEXT NOT NULL,name TEXT NOT NULL,barcode TEXT,unit TEXT NOT NULL DEFAULT 'each',selling_price_minor INTEGER NOT NULL,cost_minor INTEGER NOT NULL,tax_code_id TEXT REFERENCES tax_codes(id),inventory_account_id TEXT REFERENCES accounts(id),cogs_account_id TEXT REFERENCES accounts(id),income_account_id TEXT REFERENCES accounts(id),active INTEGER NOT NULL DEFAULT 1,UNIQUE(workspace_id,sku),UNIQUE(workspace_id,barcode));
CREATE TABLE stock_ledger(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,product_id TEXT NOT NULL REFERENCES retail_products(id),location_id TEXT NOT NULL REFERENCES locations(id),effective_at TEXT NOT NULL,quantity_delta TEXT NOT NULL,unit_cost_minor INTEGER NOT NULL,kind TEXT NOT NULL,source_type TEXT NOT NULL,source_id TEXT NOT NULL,actor_id TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(workspace_id,source_type,source_id,product_id,location_id,kind));
CREATE INDEX idx_stock_balance ON stock_ledger(workspace_id,product_id,location_id,effective_at);
CREATE TABLE purchase_orders(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,number TEXT NOT NULL,vendor_id TEXT NOT NULL REFERENCES parties(id),location_id TEXT NOT NULL REFERENCES locations(id),ordered_on TEXT NOT NULL,expected_on TEXT,status TEXT NOT NULL CHECK(status IN ('draft','approved','part_received','received','cancelled')),currency TEXT NOT NULL,created_by TEXT NOT NULL,approved_by TEXT,created_at TEXT NOT NULL,UNIQUE(workspace_id,number));
CREATE TABLE purchase_order_lines(id TEXT PRIMARY KEY,purchase_order_id TEXT NOT NULL REFERENCES purchase_orders(id),product_id TEXT NOT NULL REFERENCES retail_products(id),quantity TEXT NOT NULL,received_quantity TEXT NOT NULL DEFAULT '0',unit_cost_minor INTEGER NOT NULL,tax_code_id TEXT REFERENCES tax_codes(id));
CREATE TABLE sales(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,number TEXT NOT NULL,location_id TEXT NOT NULL REFERENCES locations(id),customer_id TEXT REFERENCES parties(id),sold_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('draft','completed','returned','voided')),currency TEXT NOT NULL,subtotal_minor INTEGER NOT NULL,tax_minor INTEGER NOT NULL,total_minor INTEGER NOT NULL,paid_minor INTEGER NOT NULL DEFAULT 0,created_by TEXT NOT NULL,approved_by TEXT,document_id TEXT REFERENCES documents(id),UNIQUE(workspace_id,number));
CREATE TABLE sale_lines(id TEXT PRIMARY KEY,sale_id TEXT NOT NULL REFERENCES sales(id),product_id TEXT NOT NULL REFERENCES retail_products(id),quantity TEXT NOT NULL,unit_price_minor INTEGER NOT NULL,discount_minor INTEGER NOT NULL,tax_minor INTEGER NOT NULL,total_minor INTEGER NOT NULL,cost_minor INTEGER NOT NULL);
CREATE TABLE tender_entries(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,sale_id TEXT REFERENCES sales(id),kind TEXT NOT NULL,amount_minor INTEGER NOT NULL,reference TEXT,received_at TEXT NOT NULL,actor_id TEXT NOT NULL);
CREATE TABLE retail_returns(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,number TEXT NOT NULL,sale_id TEXT NOT NULL REFERENCES sales(id),location_id TEXT NOT NULL REFERENCES locations(id),returned_at TEXT NOT NULL,reason TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('draft','approved','completed')),refund_minor INTEGER NOT NULL,created_by TEXT NOT NULL,approved_by TEXT,UNIQUE(workspace_id,number));
CREATE TABLE retail_return_lines(id TEXT PRIMARY KEY,return_id TEXT NOT NULL REFERENCES retail_returns(id),sale_line_id TEXT NOT NULL REFERENCES sale_lines(id),quantity TEXT NOT NULL,restock INTEGER NOT NULL DEFAULT 1);
CREATE TABLE cash_sessions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,location_id TEXT NOT NULL REFERENCES locations(id),opened_by TEXT NOT NULL,opened_at TEXT NOT NULL,opening_minor INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN ('open','closed')),closed_by TEXT,closed_at TEXT,expected_minor INTEGER,actual_minor INTEGER,variance_minor INTEGER);
CREATE TABLE credit_policies(workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,party_id TEXT NOT NULL REFERENCES parties(id),limit_minor INTEGER NOT NULL DEFAULT 0,terms_days INTEGER NOT NULL DEFAULT 0,blocked INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(workspace_id,party_id));
CREATE TABLE stock_counts(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,location_id TEXT NOT NULL REFERENCES locations(id),status TEXT NOT NULL CHECK(status IN ('draft','approved','posted')),created_by TEXT NOT NULL,approved_by TEXT,created_at TEXT NOT NULL);
CREATE TABLE stock_count_lines(id TEXT PRIMARY KEY,stock_count_id TEXT NOT NULL REFERENCES stock_counts(id),product_id TEXT NOT NULL REFERENCES retail_products(id),expected_quantity TEXT NOT NULL,counted_quantity TEXT NOT NULL);
CREATE TABLE goods_receipts(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,purchase_order_id TEXT NOT NULL REFERENCES purchase_orders(id),received_at TEXT NOT NULL,received_by TEXT NOT NULL);
CREATE TABLE three_way_matches(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,purchase_order_id TEXT NOT NULL REFERENCES purchase_orders(id),purchase_bill_id TEXT NOT NULL REFERENCES documents(id),status TEXT NOT NULL CHECK(status IN ('matched','variance')),quantity_variance TEXT NOT NULL,value_variance_minor INTEGER NOT NULL,checked_by TEXT NOT NULL,checked_at TEXT NOT NULL);
'''
