const $=s=>document.querySelector(s),params=new URLSearchParams(location.search),next=params.get('next')||'/operations';let credentials,oauth;
async function request(path,body){let r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j.error||'Could not sign in');return j}
function fail(x){$('#error').textContent=x.message||String(x)}
async function providers(){try{let r=await fetch('/api/oauth/providers'),x=await r.json(),enabled=new Set(x.providers.map(p=>p.id));if(x.saas_mode){document.body.dataset.saasMode='true';$('#new').hidden=true;$('#signup').hidden=true;if(location.hash!=='#link-existing')$('#intro-sub').textContent='Continue with Google or Microsoft to start free, or sign in below.'}document.querySelectorAll('[data-provider]').forEach(b=>{b.disabled=!enabled.has(b.dataset.provider);b.title=b.disabled?'Your Mosaic administrator has not configured this provider yet.':''})}catch(_){document.querySelectorAll('[data-provider]').forEach(b=>b.disabled=true)}}
document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>{if(b.disabled)return;let invite=params.get('invite')||'',q=new URLSearchParams({next});if(invite)q.set('invite',invite);location.href=`/oauth/${b.dataset.provider}/start?${q}`});
$('#login').onsubmit=async e=>{e.preventDefault();$('#error').textContent='';credentials={email:$('#email').value,password:$('#password').value};try{let x=await request('/api/session/options',credentials);if(x.workspaces.length===1)return enterPassword(x.workspaces[0].workspace_id);if(!x.workspaces.length)throw Error('Email or password did not match a Mosaic account');choose(x.workspaces,w=>enterPassword(w.workspace_id))}catch(x){fail(x)}};
function choose(workspaces,onpick){$('#login').hidden=true;$('#new').hidden=true;$('#link').hidden=true;$('#choose').hidden=false;$('#companies').innerHTML='';workspaces.forEach(w=>{let b=document.createElement('button');b.className='company';b.textContent=w.name+' · '+w.role;b.onclick=()=>onpick(w);$('#companies').appendChild(b)})}
async function enterPassword(workspace_id){try{let x=await request('/api/session',{...credentials,workspace_id});MosaicAuth.set(x,$('#remember').checked);location.href=params.has('next')?next:x.landing}catch(x){fail(x)}}
async function completeOAuth(code){try{let x=await request('/api/oauth/complete',{code});oauth=x;if(x.workspaces.length===1)return enterOAuth(x.workspaces[0].workspace_id);if(!x.workspaces.length)throw Error('No Mosaic company is linked to this identity');choose(x.workspaces,w=>enterOAuth(w.workspace_id))}catch(x){fail(x)}}
async function enterOAuth(workspace_id){try{let x=await request('/api/oauth/enter',{code:oauth.enter_code,workspace_id});MosaicAuth.set(x,true);location.href=params.has('next')?next:x.landing}catch(x){fail(x)}}
$('#link').onsubmit=async e=>{e.preventDefault();try{let r=await fetch('/api/oauth/link-instead',{method:'POST',headers:{'Content-Type':'application/json',...MosaicAuth.headers},body:JSON.stringify({email:$('#linkemail').value,password:$('#linkpassword').value})}),x=await r.json();if(!r.ok)throw Error(x.error||'Could not link this account');history.replaceState(null,'','/signin');completeOAuth(x.code)}catch(x){fail(x)}};
$('#new').onclick=()=>{$('#login').hidden=true;$('#new').hidden=true;$('#signup').hidden=false};$('#back').onclick=()=>{$('#signup').hidden=true;$('#login').hidden=false;$('#new').hidden=document.body.dataset.saasMode==='true'};$('#signup').onsubmit=async e=>{e.preventDefault();try{let x=await request('/api/signup',{company_name:$('#company').value,email:$('#newemail').value,password:$('#newpassword').value});MosaicAuth.set(x,true);location.href=x.landing}catch(x){fail(x)}};
if(localStorage.getItem('mosaicSignedInBefore')){$('#intro-title').textContent='Welcome back.';$('#intro-sub').textContent='Use your work email. Mosaic opens the right company and the work your role allows.'}
providers();if(location.hash==='#link-existing'){$('#login').hidden=true;$('#new').hidden=true;$('#link').hidden=false;$('#intro-title').textContent='Already with Mosaic?';$('#intro-sub').textContent='Confirm your password once to connect Google or Microsoft.'}
if(params.get('oauth'))completeOAuth(params.get('oauth'))
